### ISSUE TITLE
Examples use decorators, but decorators are not supported.

### ISSUE THREAD

**Issue by josephbhunt** [IBM/mobx-react-router#33]
While i like the fact that the examples include decorators for future javascript versions, the examples are not useful for today. Decorators are not supported in any browser right now. It would be nice to have all examples in the README written in ECMAScript 5.

**Comment by alisd23** [comment]
Hi there. I agree that decorators aren't actually in the ES spec yet, (actually still only stage 2). However I'm sort of trying to keep in sync with the `mobx-react` docs, to try and keep the documentation as similar as possible.

The `mobx-react` docs include decorators *and* es6 syntax, so maybe this would be a suitable compromise - to also show the example with es6 features only? I wouldn't want to drop back to es5 as that is pretty much entirely implemented in all the modern browsers.

**Comment by gcattan** [comment]
This seems a little outdated now. Closing.
