### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by alisd23** [IBM/mobx-react-router#74]
At the moment I just don't have any time to manage this repository, and I don't use it regularly anymore.

As this project has a reasonable amount of usage, I'm looking for maintainers to prevent it from dying. I've not been paying attention for the last few months (sorry).

I'm happy to add new collaborators (with full control) or if someone really wants (given they'll actually maintain it) I'm happy to transfer ownership.

If you're interested, drop a comment on this issue, or just email me at alisd23@live.co.uk! 👍

**Comment by jimbofreedman** [comment]
@alisd23 do you have a roadmap of things you already had planned, aside from open issues and dependency updates?

**Comment by eduardofcbg** [comment]
I would gladly maintain this, but like @jimbofreedman said,  there's not much to maintain. That is a good thing!

**Comment by alisd23** [comment]
Hi guys, sorry for taking so long to get round to this. I'm trying to run a new business so everything had been a bit crazy.

@jimbofreedman No roadmap planned specifically, I guess the goal was to keep it maintained and working, although more difficult now that I don't currently use it any projects.

@eduardofcbg That'd be really great! I'm happy to add you as a collaborator for now if that works for you?

**Comment by eduardofcbg** [comment]
Sure! I would be happy to help when needed. I'm using this in a few projects

**Comment by jimbofreedman** [comment]
I'm also still using it! I'm sure between the two of us we can keep updates under control :)

**Comment by eduardofcbg** [comment]
@jimbofreedman thats great!

**Comment by alisd23** [comment]
OK Brilliant, thanks, guys! I've invited you both to be collaborators. That should give you full control 👍 

I guess the key thing from a maintenance point of view is the [semantic releases](https://semantic-release.gitbook.io/semantic-release/) - all the detail can be found at that link.

But of course, if you have any other questions or if something isn't clear, either ask on this thread publicly or feel free to drop me an email at alisd23@live.co.uk

**Comment by jimbofreedman** [comment]
I was off the grid for a few days (ill 😢) and the invitation expired - could I have another please?

**Comment by alisd23** [comment]
@jimbofreedman No problem, another invite sent!

**Comment by mejbass** [comment]
I'm Interested

**Comment by gcattan** [comment]
@mejbass Great! I have sent you an invite.

If you are looking for a first issue, I recommend this one: https://github.com/IBM/mobx-react-router/issues/191
